In [2]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\santhosh\appdata\local\programs\python\python311\lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.23.2 in c:\users\santhosh\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\santhosh\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\santhosh\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\santhosh\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\santhosh\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

### Load and Explore

In [4]:
# Load dataset

import pandas as pd


df = pd.read_csv(r"C:\Users\Santhosh\Desktop\healthcare_data_analysis\healthcare.csv")
df.head()

,Patient_ID,Age,Gender,Symptoms,Symptom_Count,Disease
0,1,29,Male,"fever, back pain, shortness of breath",3,Allergy
1,2,76,Female,"insomnia, back pain, weight loss",3,Thyroid Disorder
2,3,78,Male,"sore throat, vomiting, diarrhea",3,Influenza
3,4,58,Other,"blurred vision, depression, weight loss, muscl...",4,Stroke
4,5,55,Female,"swelling, appetite loss, nausea",3,Heart Disease

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Patient_ID     25000 non-null  int64
 1   Age            25000 non-null  int64
 2   Gender         25000 non-null  object
 3   Symptoms       25000 non-null  object
 4   Symptom_Count  25000 non-null  int64
 5   Disease        25000 non-null  object
dtypes: int64(3), object(3)
memory usage: 1.1+ MB

In [15]:
df.isnull().sum()

Patient_ID       0
Age              0
Gender           0
Symptoms         0
Symptom_Count    0
Disease          0
dtype: int64

In [17]:
df.describe()

         Patient_ID           Age  Symptom_Count
count  25000.000000  25000.000000   25000.000000
mean   12500.500000     45.302240       5.001440
std     7217.022701     26.106224       1.415796
min        1.000000      1.000000       3.000000
25%     6250.750000     23.000000       4.000000
50%    12500.500000     45.000000       5.000000
75%    18750.250000     68.000000       6.000000
max    25000.000000     90.000000       7.000000

In [26]:
df.dtypes

Patient_ID        int64
Age               int64
Gender           object
Symptoms         object
Symptom_Count     int64
Disease          object
dtype: object

In [ ]:
male = df[df["Gender"] == "Male"]
female = df[df["Gender"] == "Female"]
other = df[df["Gender"]]

In [58]:
male.shape

(8271, 6)

In [ ]:
female.shape.

(8336, 6)